### ISSUE TITLE
jQuery not loading because of mixed content

### ISSUE THREAD

**Issue by l0b0** [smcnabb/dark-souls-cheat-sheet#4]
The tabs and Add/Edit buttons don't do anything on Firefox 40.0.3. This is because insecure mixed content is blocked:

> Blocked loading mixed active content "http://code.jquery.com/jquery-latest.js"

You can simply change it to https://code.jquery.com/jquery-latest.js to fix it

**Comment by emcniece** [comment]
Pull request submitted: https://github.com/smcnabb/dark-souls-cheat-sheet/pull/10

**Comment by smcnabb** [comment]
Thanks again!
