### ISSUE TITLE
Wiki links broken

### ISSUE THREAD

**Issue by icheyne** [smcnabb/dark-souls-cheat-sheet#7]
All the wiki links are broken.

> ERROR
> The request could not be satisfied.
> Request blocked.
> 
> Generated by cloudfront (CloudFront)
> Request ID: APKptbF-L2G2ESfjyZDjdkThOUhvnGYdx0VMWsx_QOBb8dqs648ClA==

BTW, thanks so much for putting this list together. Makes Dark Souls much more pleasurable for a newbie with a busy life who isn't interested in flailing about.

**Comment by smcnabb** [comment]
I know this is ancient but thanks anyway. Fixed.
